import { getChatGPTUser } from '@/app/chatgpt-auth';
import { all,one,run,bucket,choice,fail } from '@/lib/server';
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)fail('Sign in to upload music.',401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)fail('Request not allowed.',403);if(Number(req.headers.get('content-length'))>26*1024*1024)fail('Choose a file smaller than 25 MB.',413);
const form=await req.formData(),file=form.get('file');const purpose=choice(form.get('purpose'),['audio','avatar']);if(!(file instanceof File)||file.size===0)fail('Choose a file.');if(file.size>(purpose==='avatar'?3:25)*1024*1024)fail(purpose==='avatar'?'Choose a photo smaller than 3 MB.':'Choose audio smaller than 25 MB.',413);
const quota=await one('SELECT COALESCE(SUM(size),0) AS total FROM files WHERE owner=?',user.userId);if(quota.total+file.size>500*1024*1024)fail('Your 500 MB preview storage is full.');
const bytes=new Uint8Array(await file.slice(0,32).arrayBuffer());const text=new TextDecoder('latin1').decode(bytes);let mime='';
if(purpose==='avatar'){if(bytes[0]===137&&text.slice(1,4)==='PNG')mime='image/png';else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime='image/jpeg';else if(text.startsWith('RIFF')&&text.slice(8,12)==='WEBP')mime='image/webp';else fail('Use a PNG, JPEG or WebP photo.');}
else{if(text.startsWith('RIFF')&&text.slice(8,12)==='WAVE')mime='audio/wav';else if(text.startsWith('ID3')||(bytes[0]===255&&(bytes[1]&224)===224))mime='audio/mpeg';else if(text.startsWith('OggS'))mime='audio/ogg';else if(text.startsWith('fLaC'))mime='audio/flac';else if(bytes[0]===26&&bytes[1]===69&&bytes[2]===223&&bytes[3]===163)mime='audio/webm';else if(text.slice(4,8)==='ftyp')mime='audio/mp4';else fail('Use WAV, MP3, OGG, FLAC, WebM or M4A audio.');}
const id=crypto.randomUUID();await bucket().put(id,file.stream(),{httpMetadata:{contentType:mime}});try{await run('INSERT INTO files (id,owner,name,mime,size,purpose,created) VALUES (?,?,?,?,?,?,?)',id,user.userId,file.name.slice(0,180),mime,file.size,purpose,Date.now());}catch(e){await bucket().delete(id);throw e;}
return Response.json({id,name:file.name,mime});
}catch(e:any){if(!e.status)console.error('Upload failed',e);return Response.json({error:e.status?e.message:'Upload failed. Try a smaller file.'},{status:e.status||500});}}
