-- Generated from the final append-only D1 migrations. Fresh SESSION database only.
CREATE OR REPLACE FUNCTION session_json_extract(input text, field text) RETURNS text
   LANGUAGE sql IMMUTABLE AS $$ SELECT input::jsonb ->> field $$;

CREATE OR REPLACE FUNCTION session_json_array_length(input text, field text) RETURNS integer
   LANGUAGE sql IMMUTABLE AS $$ SELECT jsonb_array_length(input::jsonb -> field) $$;

CREATE OR REPLACE FUNCTION session_json_each(input text) RETURNS TABLE(value text)
   LANGUAGE sql IMMUTABLE AS $$ SELECT item #>> '{}' FROM jsonb_array_elements(input::jsonb) item $$;

CREATE TABLE IF NOT EXISTS "comments" (
  "id" TEXT NOT NULL,
  "track" TEXT NOT NULL,
  "user" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "room" TEXT NOT NULL,
  "sender" TEXT NOT NULL,
  "recipient" TEXT,
  "kind" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  "clientId" TEXT,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "files" (
  "id" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "mime" TEXT NOT NULL,
  "size" BIGINT NOT NULL,
  "purpose" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "follows" (
  "user" TEXT NOT NULL,
  "target" TEXT NOT NULL,
  PRIMARY KEY ("user","target")
);

CREATE TABLE IF NOT EXISTS "members" (
  "room" TEXT NOT NULL,
  "user" TEXT NOT NULL,
  "seen" BIGINT NOT NULL,
  PRIMARY KEY ("room","user")
);

CREATE TABLE IF NOT EXISTS "profiles" (
  "id" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "roles" TEXT NOT NULL,
  "bio" TEXT NOT NULL DEFAULT '',
  "location" TEXT NOT NULL DEFAULT '',
  "visibility" TEXT NOT NULL DEFAULT 'private',
  "avatar" TEXT,
  "created" BIGINT NOT NULL,
  "rates" TEXT NOT NULL DEFAULT '[]',
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "project_files" (
  "project" TEXT NOT NULL,
  "file" TEXT NOT NULL,
  PRIMARY KEY ("project","file")
);

CREATE TABLE IF NOT EXISTS "projects" (
  "id" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "updated" BIGINT NOT NULL,
  "revision" BIGINT NOT NULL DEFAULT 0,
  "updatedBy" TEXT,
  "lastSaveId" TEXT,
  "forkedFrom" TEXT,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "reports" (
  "id" TEXT NOT NULL,
  "user" TEXT NOT NULL,
  "track" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "rooms" (
  "id" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "project" TEXT,
  "invite" TEXT NOT NULL,
  "expires" BIGINT NOT NULL,
  "created" BIGINT NOT NULL,
  "visibility" TEXT NOT NULL DEFAULT 'invite',
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "saved" (
  "user" TEXT NOT NULL,
  "track" TEXT NOT NULL,
  PRIMARY KEY ("user","track")
);

CREATE TABLE IF NOT EXISTS "tracks" (
  "id" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "genre" TEXT NOT NULL,
  "bpm" BIGINT NOT NULL,
  "musicalKey" TEXT NOT NULL,
  "visibility" TEXT NOT NULL DEFAULT 'private',
  "permission" TEXT NOT NULL DEFAULT 'listen',
  "fileId" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  "price" BIGINT,
  "plays" BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "media_sessions" (
  "room" TEXT NOT NULL,
  "user" TEXT NOT NULL,
  "session" TEXT NOT NULL,
  "seen" BIGINT NOT NULL,
  "sharing" BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("room","user")
);

CREATE TABLE IF NOT EXISTS "project_versions" (
  "id" TEXT NOT NULL,
  "project" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  "author" TEXT,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "rate_limits" (
  "id" TEXT NOT NULL,
  "count" BIGINT NOT NULL,
  "expires" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "room_editors" (
  "room" TEXT NOT NULL,
  "project" TEXT NOT NULL,
  "user" TEXT NOT NULL,
  "grantedBy" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("room","project","user")
);

CREATE TABLE IF NOT EXISTS "project_creations" (
  "owner" TEXT NOT NULL,
  "creationKey" TEXT NOT NULL,
  "project" TEXT NOT NULL,
  "requestHash" TEXT NOT NULL,
  "revision" BIGINT NOT NULL,
  "created" BIGINT NOT NULL,
  "deletedAt" BIGINT,
  PRIMARY KEY ("owner","creationKey")
);

CREATE TABLE IF NOT EXISTS "take_bank_files" (
  "bank" TEXT NOT NULL,
  "take" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "project" TEXT NOT NULL,
  "file" TEXT NOT NULL,
  "hash" TEXT NOT NULL,
  "size" BIGINT NOT NULL,
  "frames" BIGINT NOT NULL,
  "sampleRate" BIGINT NOT NULL,
  "depth" BIGINT NOT NULL,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("bank","take")
);

CREATE TABLE IF NOT EXISTS "take_banks" (
  "id" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "project" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "revision" BIGINT NOT NULL,
  "updated" BIGINT NOT NULL,
  "lastSaveId" TEXT NOT NULL,
  "deletedAt" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "collaboration_requests" (
  "id" TEXT NOT NULL,
  "sender" TEXT NOT NULL,
  "recipient" TEXT NOT NULL,
  "track" TEXT,
  "role" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "created" BIGINT NOT NULL,
  "updated" BIGINT NOT NULL,
  "trackTitle" TEXT,
  "scopeKey" TEXT NOT NULL DEFAULT '',
  "senderName" TEXT NOT NULL DEFAULT 'SESSION member',
  "senderUsername" TEXT NOT NULL DEFAULT 'member',
  "senderAvatar" TEXT,
  "recipientName" TEXT NOT NULL DEFAULT 'SESSION member',
  "recipientUsername" TEXT NOT NULL DEFAULT 'member',
  "recipientAvatar" TEXT,
  "operationId" TEXT,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "direct_messages" (
  "id" TEXT NOT NULL,
  "request" TEXT NOT NULL,
  "sender" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  "clientId" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "id" TEXT NOT NULL,
  "user" TEXT NOT NULL,
  "actor" TEXT,
  "kind" TEXT NOT NULL,
  "resourceType" TEXT NOT NULL,
  "resourceId" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  "readAt" BIGINT,
  "uniqueKey" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_blocks" (
  "user" TEXT NOT NULL,
  "target" TEXT NOT NULL,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("user","target")
);

CREATE TABLE IF NOT EXISTS "stripe_accounts" (
  "user" TEXT NOT NULL,
  "accountId" TEXT NOT NULL,
  "chargesEnabled" BIGINT NOT NULL DEFAULT 0,
  "payoutsEnabled" BIGINT NOT NULL DEFAULT 0,
  "details" TEXT NOT NULL DEFAULT '{}',
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("user")
);

CREATE TABLE IF NOT EXISTS "orders" (
  "id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "track" TEXT,
  "seller" TEXT NOT NULL,
  "buyer" TEXT NOT NULL,
  "serviceSnapshot" TEXT NOT NULL DEFAULT '{}',
  "amountCents" BIGINT NOT NULL,
  "feeCents" BIGINT NOT NULL DEFAULT 0,
  "currency" TEXT NOT NULL DEFAULT 'usd',
  "status" TEXT NOT NULL DEFAULT 'pending',
  "stripeSessionId" TEXT NOT NULL DEFAULT '',
  "paymentIntent" TEXT,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "stripe_events" (
  "eventId" TEXT NOT NULL,
  "processedAt" BIGINT NOT NULL,
  PRIMARY KEY ("eventId")
);

CREATE TABLE IF NOT EXISTS "posts" (
  "id" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "fileId" TEXT NOT NULL,
  "track" TEXT,
  "caption" TEXT NOT NULL DEFAULT '',
  "visibility" TEXT NOT NULL DEFAULT 'public',
  "plays" BIGINT NOT NULL DEFAULT 0,
  "created" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "post_likes" (
  "user" TEXT NOT NULL,
  "post" TEXT NOT NULL,
  PRIMARY KEY ("user","post")
);

CREATE INDEX IF NOT EXISTS "idx_comments_track" ON "comments" ("track");

CREATE INDEX IF NOT EXISTS "idx_events_room_id" ON "events" ("room","id");

CREATE INDEX IF NOT EXISTS "idx_files_owner" ON "files" ("owner");

CREATE INDEX IF NOT EXISTS "idx_members_user" ON "members" ("user");

CREATE UNIQUE INDEX IF NOT EXISTS "profiles_username_unique" ON "profiles" ("username");

CREATE INDEX IF NOT EXISTS "idx_project_files_file" ON "project_files" ("file");

CREATE INDEX IF NOT EXISTS "idx_projects_owner" ON "projects" ("owner");

CREATE INDEX IF NOT EXISTS "idx_tracks_visibility" ON "tracks" ("visibility");

CREATE INDEX IF NOT EXISTS "idx_tracks_owner" ON "tracks" ("owner");

CREATE INDEX IF NOT EXISTS "idx_tracks_file" ON "tracks" ("fileId");

CREATE INDEX IF NOT EXISTS "idx_versions_project" ON "project_versions" ("project");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_events_dedup" ON "events" ("room","sender","clientId");

CREATE INDEX IF NOT EXISTS "idx_room_editors_project_user" ON "room_editors" ("project","user");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_project_creations_project" ON "project_creations" ("project");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_take_bank_files_file" ON "take_bank_files" ("file");

CREATE INDEX IF NOT EXISTS "idx_take_bank_files_owner" ON "take_bank_files" ("owner");

CREATE INDEX IF NOT EXISTS "idx_take_banks_owner" ON "take_banks" ("owner");

CREATE INDEX IF NOT EXISTS "idx_collaboration_recipient" ON "collaboration_requests" ("recipient","status","updated");

CREATE INDEX IF NOT EXISTS "idx_collaboration_sender" ON "collaboration_requests" ("sender","updated");

CREATE INDEX IF NOT EXISTS "idx_collaboration_track" ON "collaboration_requests" ("track");

CREATE INDEX IF NOT EXISTS "idx_direct_messages_request" ON "direct_messages" ("request","created");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_direct_messages_dedup" ON "direct_messages" ("request","sender","clientId");

CREATE INDEX IF NOT EXISTS "idx_notifications_user_created" ON "notifications" ("user","created");

CREATE INDEX IF NOT EXISTS "idx_notifications_user_read" ON "notifications" ("user","readAt","created");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_notifications_unique" ON "notifications" ("uniqueKey");

CREATE INDEX IF NOT EXISTS "idx_user_blocks_target" ON "user_blocks" ("target");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_collaboration_active_track_unique" ON "collaboration_requests" ("sender","recipient","track") WHERE "collaboration_requests"."status" IN ('pending','accepted') AND "collaboration_requests"."track" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_collaboration_active_profile_unique" ON "collaboration_requests" ("sender","recipient") WHERE "collaboration_requests"."status" IN ('pending','accepted') AND "collaboration_requests"."track" IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_collaboration_active_scope_unique" ON "collaboration_requests" ("scopeKey") WHERE "collaboration_requests"."status" IN ('pending','accepted');

CREATE INDEX IF NOT EXISTS "idx_orders_seller_created" ON "orders" ("seller","created");

CREATE INDEX IF NOT EXISTS "idx_orders_buyer_created" ON "orders" ("buyer","created");

CREATE INDEX IF NOT EXISTS "idx_orders_session" ON "orders" ("stripeSessionId");

CREATE INDEX IF NOT EXISTS "idx_posts_owner_created" ON "posts" ("owner","created");

CREATE INDEX IF NOT EXISTS "idx_posts_visibility_created" ON "posts" ("visibility","created");

CREATE INDEX IF NOT EXISTS "idx_post_likes_post" ON "post_likes" ("post");

CREATE TABLE IF NOT EXISTS upload_sessions (
  id TEXT PRIMARY KEY, owner TEXT NOT NULL, metadata TEXT NOT NULL, size BIGINT NOT NULL,
  parts BIGINT NOT NULL, expires BIGINT NOT NULL, status TEXT NOT NULL DEFAULT 'pending');

CREATE INDEX IF NOT EXISTS upload_sessions_owner ON upload_sessions(owner);
