import { defaultPattern,type Track } from './catalog';
export type MixerTrack={id:string;name:string;fileId?:string;demo?:string;sequence?:number[][];volume:number;pan:number;muted:boolean;solo:boolean;offset:number;trimStart:number;trimEnd:number;low:number;mid:number;high:number;duration?:number;peaks?:number[]};
export type Arrangement={bpm:number;tracks:MixerTrack[]};
let audio:AudioContext|null=null;const cache=new Map<string,AudioBuffer>();
export function context(){if(!audio)audio=new AudioContext();return audio;}
export function trackFrom(t:Track):MixerTrack{return {id:crypto.randomUUID(),name:t.title,fileId:t.fileId,demo:t.demo?t.id:undefined,volume:.8,pan:0,muted:false,solo:false,offset:0,trimStart:0,trimEnd:0,low:0,mid:0,high:0};}
export function instrument(c:BaseAudioContext,dest:AudioNode,index:number,time:number,volume=1){
const gain=c.createGain();gain.connect(dest);
if(index===0){const osc=c.createOscillator();osc.frequency.setValueAtTime(145,time);osc.frequency.exponentialRampToValueAtTime(43,time+.18);gain.gain.setValueAtTime(.7*volume,time);gain.gain.exponentialRampToValueAtTime(.0001,time+.34);osc.connect(gain);osc.start(time);osc.stop(time+.36);}
else{const length=index===1?.16:.045;const buffer=c.createBuffer(1,Math.floor(c.sampleRate*length),c.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const source=c.createBufferSource();source.buffer=buffer;const filter=c.createBiquadFilter();filter.type='highpass';filter.frequency.value=index===1?1100:7500;gain.gain.setValueAtTime((index===1?.3:.15)*volume,time);source.connect(filter).connect(gain);source.start(time);}
}
export async function synth(bpm:number,pattern=defaultPattern,demo?:string){const c=new OfflineAudioContext(2,Math.ceil((60/bpm*32+1)*44100),44100);const master=c.createGain();master.gain.value=.7;master.connect(c.destination);const step=60/bpm/4;
for(let bar=0;bar<8;bar++)for(let i=0;i<16;i++)for(let row=0;row<3;row++)if(pattern[row]?.[i])instrument(c,master,row,(bar*16+i)*step,.8);
if(demo){const roots=demo==='demo-1'?[87.307,69.296,103.826,77.782]:demo==='demo-3'?[73.416,65.406,87.307,65.406]:demo==='demo-4'?[55,65.406,73.416,65.406]:[65.406,77.782,58.27,69.296];for(let bar=0;bar<8;bar++){const start=bar*16*step;const freq=roots[bar%4];for(const ratio of [1,1.1892,1.4983,2]){const osc=c.createOscillator(),g=c.createGain(),f=c.createBiquadFilter();osc.type='triangle';osc.frequency.value=freq*ratio*2;f.type='lowpass';f.frequency.value=1200;g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(.035,start+.07);g.gain.exponentialRampToValueAtTime(.0001,start+16*step);osc.connect(f).connect(g).connect(master);osc.start(start);osc.stop(start+16*step+.01);}for(let beat=0;beat<4;beat++){const osc=c.createOscillator(),g=c.createGain();const at=start+beat*4*step;osc.frequency.value=freq/2;g.gain.setValueAtTime(.22,at);g.gain.exponentialRampToValueAtTime(.001,at+3*step);osc.connect(g).connect(master);osc.start(at);osc.stop(at+4*step);}}}
return c.startRendering();}
export async function bufferFor(t:MixerTrack,bpm:number){const key=t.fileId||`${t.demo||'seq'}-${bpm}-${JSON.stringify(t.sequence||[])}`;if(cache.has(key))return cache.get(key)!;let b:AudioBuffer;if(t.fileId){const r=await fetch('/api/file/'+t.fileId);if(!r.ok)throw new Error('This audio is private or is no longer available.');b=await context().decodeAudioData(await r.arrayBuffer());}else b=await synth(bpm,t.sequence||defaultPattern,t.demo);cache.set(key,b);return b;}
export function peaks(b:AudioBuffer){const d=b.getChannelData(0),out=[];for(let i=0;i<120;i++){const begin=Math.floor(i*d.length/120),end=Math.floor((i+1)*d.length/120);let peak=0;for(let j=begin;j<end;j+=Math.max(1,Math.floor((end-begin)/100)))peak=Math.max(peak,Math.abs(d[j]));out.push(peak);}return out;}
export function connectTrack(c:BaseAudioContext,src:AudioBufferSourceNode,t:MixerTrack,dest:AudioNode){let node:AudioNode=src;for(const [type,freq,gain] of [['lowshelf',200,t.low],['peaking',1200,t.mid],['highshelf',5000,t.high]] as const){const eq=c.createBiquadFilter();eq.type=type;eq.frequency.value=freq;eq.gain.value=gain||0;node.connect(eq);node=eq;}const pan=c.createStereoPanner();pan.pan.value=Math.max(-1,Math.min(1,t.pan));node.connect(pan);const g=c.createGain();g.gain.value=t.volume;pan.connect(g).connect(dest);}
export async function playMix(data:Arrangement,onEnd?:()=>void){const c=context();await c.resume();const tracks=data.tracks.filter(t=>!t.muted&&(!data.tracks.some(x=>x.solo)||t.solo));if(!tracks.length)throw new Error('Add or unmute a track to play.');const loaded=await Promise.all(tracks.map(async t=>({t,b:await bufferFor(t,data.bpm)})));const master=c.createDynamicsCompressor();master.threshold.value=-3;master.ratio.value=12;master.connect(c.destination);const nodes:AudioBufferSourceNode[]=[];let duration=0;const when=c.currentTime+.08;
for(const {t,b} of loaded){const length=Math.max(0,b.duration-t.trimStart-(t.trimEnd||0));if(length<=0)continue;const s=c.createBufferSource();s.buffer=b;connectTrack(c,s,t,master);s.start(when+t.offset,t.trimStart,length);nodes.push(s);duration=Math.max(duration,t.offset+length);}const timer=setTimeout(()=>{master.disconnect();onEnd?.();},(duration+.2)*1000);let stopped=false;return {duration,start:performance.now(),stop:()=>{if(stopped)return;stopped=true;clearTimeout(timer);for(const n of nodes){try{n.stop();}catch{}}master.disconnect();}};}
export async function renderMix(data:Arrangement){const tracks=data.tracks.filter(t=>!t.muted&&(!data.tracks.some(x=>x.solo)||t.solo));if(!tracks.length)throw new Error('Add or unmute a track first.');const loaded=await Promise.all(tracks.map(async t=>({t,b:await bufferFor(t,data.bpm)})));const duration=Math.min(180,Math.max(...loaded.map(({t,b})=>t.offset+b.duration-t.trimStart-(t.trimEnd||0))));if(duration<=0)throw new Error('The arrangement is empty.');const c=new OfflineAudioContext(2,Math.ceil(duration*44100),44100);const master=c.createDynamicsCompressor();master.threshold.value=-3;master.ratio.value=12;master.connect(c.destination);for(const {t,b} of loaded){const s=c.createBufferSource();s.buffer=b;connectTrack(c,s,t,master);const length=b.duration-t.trimStart-(t.trimEnd||0);if(length>0)s.start(t.offset,t.trimStart,length);}return wav(await c.startRendering());}
export function wav(b:AudioBuffer){const n=b.length,buffer=new ArrayBuffer(44+n*4),view=new DataView(buffer);function word(at:number,s:string){for(let i=0;i<s.length;i++)view.setUint8(at+i,s.charCodeAt(i));}word(0,'RIFF');view.setUint32(4,36+n*4,true);word(8,'WAVE');word(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,2,true);view.setUint32(24,b.sampleRate,true);view.setUint32(28,b.sampleRate*4,true);view.setUint16(32,4,true);view.setUint16(34,16,true);word(36,'data');view.setUint32(40,n*4,true);for(let i=0;i<n;i++)for(let ch=0;ch<2;ch++){const v=Math.max(-1,Math.min(1,b.getChannelData(Math.min(ch,b.numberOfChannels-1))[i]));view.setInt16(44+i*4+ch*2,v<0?v*32768:v*32767,true);}return new Blob([buffer],{type:'audio/wav'});}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
